#!/bin/sh
set -e

if [ "$QT_SELECT" = "qt4" ]; then
    sudo apt-get update
    sudo apt-get install libqt4-dev libqt4-sql-mysql libqt4-sql-psql libqt4-sql-sqlite libqt4-sql-odbc lcov odbcinst libmyodbc odbc-postgresql
else
    sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
    sudo apt-get update
    sudo apt-get install qtbase5-dev qtscript5-dev libqt5sql5-mysql libqt5sql5-psql libqt5sql5-sqlite libqt5sql5-odbc lcov odbcinst libmyodbc odbc-postgresql
fi

# setup odbc drivers
cat <<EOF >> template.ini
[MySQL]
Description     = ODBC for MySQL
Driver          = /usr/lib/x86_64-linux-gnu/odbc/libmyodbc.so
Setup           = /usr/lib/x86_64-linux-gnu/odbc/libodbcmyS.so
FileUsage       = 1
Threading       = 1

[PostgreSQL Unicode]
Description     = PostgreSQL ODBC driver (Unicode version)
Driver          = psqlodbcw.so
Setup           = libodbcpsqlS.so
Debug           = 0
CommLog         = 1

[PostgreSQL ANSI]
Description     = PostgreSQL ODBC driver (Unicode version)
Driver          = psqlodbca.so
Setup           = libodbcpsqlS.so
Debug           = 0
CommLog         = 1
EOF

sudo odbcinst -i -d -f template.ini

